services:
  transactions-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transactions-service
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
      - SERVER_PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/swagger-ui.html"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
